name: Tests - OS X

on: [push]

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      # - uses: actions/cache@v1
      #   id: cache-build
      #   with:
      #     path: ~/.cache/sccache
      #     key: sccache-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      #     restore-keys: |
      #       sccache-cache-${{ runner.os }}-
      # - uses: actions/cache@v1
      #   id: cache-sccache
      #   with:
      #     path: ~/sccache
      #     key: sccache-${{ runner.os }}
      # - name: restore sccache
      #   if: steps.cache-sccache.outputs.cache-hit == 'true'
      #   run: cp ~/sccache/* ~/.cargo/bin
      # - name: install sccache
      #   if: steps.cache-sccache.outputs.cache-hit != 'true'
      #   run: cargo install sccache
      # - name: Prepare sccache command bin for cache
      #   if: steps.cache-sccache.outputs.cache-hit != 'true'
      #   run: mkdir ~/sccache; cp ~/.cargo/bin/sccache ~/sccache
      - name: Run tests
        # env:
        #   RUSTC_WRAPPER: sccache
        run: cargo test --all
    
