name: Tests

on: [push, pull_request]

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
      - name: extract cpuid flags
        id: extract-cpuid-flags
        run: echo "flags=$(grep '^flags' /proc/cpuinfo | head -n1)" >> $GITHUB_OUTPUT
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{steps.extract-cpuid-flags.outputs.flags }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      # investigating a SIGILL when building our lalrpop grammar
      - name: check CPU
        run: cat /proc/cpuinfo
      - name: Generate code coverage
        env:
          RUSTFLAGS: -D warnings -C target-cpu=native
          RUST_BACKTRACE: full
        run: cargo llvm-cov --verbose --workspace --lcov --output-path lcov.txt --locked
      - uses: codecov/codecov-action@v3
        with:
          files: ./lcov.txt # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)      
