name: Tests

on: [push, pull_request]

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install deps
        run: sudo apt-get -qy update && sudo apt-get install -y && libssl-dev libssl1.1; sudo apt-get clean
      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - name: Instasll cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        env:
          RUSTFLAGS: -D warnings -C target-cpu=native
          RUST_BACKTRACE: full
        run: cargo llvm-cov --verbose --lcov --output-path lcov.txt --locked
      - uses: codecov/codecov-action@v4
        attempt_limit: 6
        attempt_delay: 10000
        with: |
          files: ./lcov.txt # optional
          fail_ci_if_error: #{{ github.event_name == 'pull_request' }}
          verbose: true # optional (default = false)      
