name: Tests

on: [push, pull_request]

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install deps [Linux]
        run: |
            sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test --all --locked
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install deps
        run: |
            sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        env:
          RUSTFLAGS: -C target-cpu=native
        with:
          version: '0.19.0'
          args: ' --avoid-cfg-tarpaulin --exclude-files target* --all --out Lcov'
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          path-to-lcov: ./lcov.info
